# Generated by Django 5.0.12 on 2025-03-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='departments',
            fields=[
                ('id_departments', models.IntegerField(primary_key=True, serialize=False)),
                ('name_departments', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='jobs',
            fields=[
                ('id_jobs', models.IntegerField(primary_key=True, serialize=False)),
                ('name_jobs', models.CharField(max_length=100)),
            ],
        ),
    ]
